### ISSUE TITLE
Not working random

### ISSUE THREAD

**Issue by anton2007** [nanochess/bootBASIC#1]
Random not implemented?
![Screenshot_2020-08-29_201451](https://user-images.githubusercontent.com/37032392/91637684-66ac7a80-ea34-11ea-9995-fe185ac981ca.jpg)

**Comment by nanochess** [comment]
Hi. This is an integer subset of BASIC. However I've optimized the code and added a RND function without arguments that returns a value between 0 to 255. I've added a "guess the dice" game to the examples.
