### ISSUE TITLE
Deleting a char on the screen

### ISSUE THREAD

**Issue by Luidenka** [nanochess/bootBASIC#2]
Hi, 

I modified the asm file so that when input can delete a character on screen, but I get this error;
`basic_test.asm:609: error: TIMES value -18 is negative`
May I ask how to solve?

Code:
```asm
backspace:
        cmp al, 0x08
        jne del
del:
        mov ah, 0x0e
        mov al, 0x08
        int 0x10

        mov al, ' '
        int 0x10

        mov al, 0x08
        int 0x10
```

**Comment by nanochess** [comment]
There is a TIMES directive at the bottom of the BASIC interpreter that fills it to a 512-byte sector. As the code you've inserted makes it larger than 512 bytes, the TIMES directive fails. My suggestion is to make it a COM file (there is the option in the code) instead of a boot sector.
